app_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_forum.urls as app_forum
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^forum/', include(app_forum,namespace='app_forum')),
    url(r'^$', RedirectView.as_view(url='/forum/', permanent='true'), name='index'),
]

app_forum/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
    company_id = models.IntegerField()
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_home/models.py
from django.db import models

# Create your models here.

app_profile/models.py
from django.db import models

# Create your models here.

app_forum/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi...'
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

app_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Forum_Lowongan
from .models import Forum


# Create your views here.
response = {}
def index(request):
    forum_list = Forum.objects.all()
    forum_latest = forum_list[::-1]
    page = request.GET.get('page', 1)
    paginator = Paginator(forum_latest, 5)
    try:
        forum = paginator.page(page)
    except PageNotAnInteger:
        forum = paginator.page(1)
    except EmptyPage:
        forum = paginator.page(paginator.num_pages)
    response['forum'] = forum
    response['forum_lowongan'] = Forum_Lowongan
    html = 'app_forum/app_forum.html'
    return render(request, html, response)

def add_forum(request):
    form = Forum_Lowongan(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['lowongan']
        forum = Forum(lowongan=response['lowongan'])
        forum.save()
        return HttpResponseRedirect('/forum/')
    else:
        return HttpResponseRedirect('/forum/')

def paginate_page(page, data_list):
    paginator = Paginator(data_list,10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # index of current page
    index = data.number - 1
    # maximum page
    max_index = len(paginator.page_range)
    # range of 10, slicing
    start_index = index if index >= 10 else 0
    end_index = 10 if index < max_index - 10 else max_index
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data': data, 'page_range': page_range}
    return paginate_data

app_home/views.py
from django.shortcuts import render

# Create your views here.

app_profile/views.py
from django.shortcuts import render

# Create your views here.

app_forum/templates/app_forum/app_forum.html
{% extends "tugas2/layout/base.html" %} {% load staticfiles%} {% block content %}
<h1 class="main-title">Forum Lowongan</h1>
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app_forum:add_forum' %}">
            <h2>Input Todo</h2>
            {% csrf_token %} {{ forum_lowongan }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My List</h2>
        <div class="forum-lowongan">
            {% if forum %} {% for data in forum %}
            <p>{{ data.lowongan }}</p>
            {% endfor %} {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}

            <div class="pagination">
                <span class="step-links">
                    <ul class="pagination">
                    {% if forum.has_previous %}
                        <li><a href="?page=1">&laquo; first</a></li>
                        <li><a href="?page={{ forum.previous_page_number }}">previous</a></li>
                    {% endif %}
                    <li><span class="current">Page {{ forum.number }} of {{ forum.paginator.num_pages }}</span></li>
                    {% if forum.has_next %}
                        <li><a href="?page={{ forum.next_page_number }}">next</a></li>
                        <li><a href="?page={{ forum.next_page_number }}">last &raquo;</a></li>
                    {% endif %}
                    </ul>
                </span>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app_home/templates/app_home/app_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app_profile/templates/app_profile/app_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/tugas2/layout/base.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- bootstrap css -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Snippet" rel="stylesheet">
	{% block styles %}
	{% endblock %}
	<title>
        {% block title %} PPW A12 {% endblock %}
    </title>
</head>

<body class="Site">
    <header>
        {% include "tugas2/partials/header.html" %}
    </header>

    <content class="Site-content">
        {% block content %}
        <!-- content goes here -->
        {% endblock %}
    </content>
    <footer class="footer">
        {% block footer %} {% include "tugas2/partials/footer.html" %} {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	{% block script %}
	{% endblock %}
</body>

templates/tugas2/partials/footer.html
{% load staticfiles %} {% load static %}
<div class="footer">
    <p>TEST FOOTER</p>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</script>

templates/tugas2/partials/header.html
<!-- templates/partials/header.html -->
{% load staticfiles %} {% load static %}

<nav class="navbar navbar-default navbar-fixed-top" style="background-color: #2E3131">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            <div>
                <p class="navbar-brand">Hehe</p>
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

			</ul>
        </div>
    </div>
</nav>